Models/Players.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lab1_KASR_MAGZ.Models
{
    public class Players
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public string Position { get; set; }

        [Required]
        public double Salary { get; set; }

        [Required]
        public string Club { get; set; }


    }
}

Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab1_KASR_MAGZ.Models.Data;
using Lab1_KASR_MAGZ.Models;
using ListLibrary;
using System.IO;
using System.Data;
using Microsoft.AspNetCore.Hosting;
using System.Diagnostics;

namespace Lab1_KASR_MAGZ.Controllers
{
    public class PlayersController : Controller
    {        

        private IHostingEnvironment Environment;
        Stopwatch timer = new Stopwatch();
        

        public PlayersController(IHostingEnvironment _environment)
        {
            Environment = _environment;
        }

        // GET: Players
        public ActionResult Index()
        {
            if(Singleton.Instance.player_list.Count() != 0)
            {
                return View(Singleton.Instance.player_list);
            }
            else
            {
                return View(Singleton.Instance.PlayerList);
            }
            
        }

        [HttpPost]
        public IActionResult Index(IFormFile postedFile)
        {
            if(Singleton.Instance.PlayerList.Count != 0 || Singleton.Instance.player_list.Count() != 0)
            {
                timer.Start();
                bool TypeListArt = false;
                int IdNumber = 0;
                int NumberListCraft = Singleton.Instance.player_list.GetCount;
                int NumberListC = Singleton.Instance.PlayerList.Count;
                string ListType = "";

                if (NumberListCraft != 0)
                {
                    TypeListArt = true;
                    if (NumberListCraft == 1 && Singleton.Instance.player_list.First().Id == 0)
                    {
                        IdNumber = 0;
                        ListType = "Lista Artesanal. ";
                        Singleton.Instance.player_list.ExtractAtStart();
                    }
                    else
                    {
                        IdNumber = NumberListCraft + 1;
                    }

                }


                if (NumberListC != 0)
                {
                    if (NumberListC == 1 && Singleton.Instance.PlayerList.First().Id == 0)
                    {
                        IdNumber = 0;
                        ListType = "Lista C#. ";
                        Singleton.Instance.PlayerList.RemoveFirst();
                    }
                    else
                    {
                        IdNumber = Singleton.Instance.PlayerList.Count + 1;
                    }
                }

                if (postedFile != null)
                {
                    string path = Path.Combine(this.Environment.WebRootPath, "Uploads");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    string fileName = Path.GetFileName(postedFile.FileName);
                    string filePath = Path.Combine(path, fileName);

                    using (FileStream stream = new FileStream(filePath, FileMode.Create))
                    {
                        postedFile.CopyTo(stream);
                    }
                    string csvData = System.IO.File.ReadAllText(filePath);

                    StreamReader streamReader = new StreamReader(filePath);
                    string lineaActual;

                    while (!streamReader.EndOfStream)
                    {
                        lineaActual = streamReader.ReadLine();

                        IdNumber += 1;
                        string[] FileInformationList = lineaActual.Split(',');
                        string FileName = FileInformationList[2];
                        string FileLastName = FileInformationList[1];
                        string FilePosition = FileInformationList[3];
                        double FileSalary = Convert.ToDouble(FileInformationList[4]);
                        string FileClub = FileInformationList[0];

                        var FilePlayer = new Models.Players
                        {
                            Id = IdNumber,
                            Name = FileName,
                            LastName = FileLastName,
                            Position = FilePosition,
                            Salary = FileSalary,
                            Club = FileClub
                        };

                        if (TypeListArt == true)
                        {
                            Singleton.Instance.player_list.InsertAtEnd(FilePlayer);
                        }
                        else
                        {
                            Singleton.Instance.PlayerList.AddLast(FilePlayer);
                        }
                    }

                    //MIDIENDO TIEMPO Y GUARDARLO
                    timer.Stop();
                    var NewDescriptionTime = new Models.TimeDescription
                    {
                        DescriptionTime = ListType + "Carga de datos por archivo ",
                        NumberTime = Convert.ToString(timer.Elapsed.TotalMilliseconds)
                    };
                    Singleton.Instance.OperationTime.Add(NewDescriptionTime);

                    return RedirectToAction(nameof(Index));

                }
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Players/Details/5
        public ActionResult Details(int id)
        {
            if (Singleton.Instance.PlayerList.Count != 0)
            {
                int pos = 0;
                bool Finding = false;
                while (Finding == false)
                {
                    if (Convert.ToInt32(Singleton.Instance.PlayerList.ElementAt(pos).Id) == id)
                    {
                        Finding = true;
                    }
                    else
                    {
                        pos++;
                    }
                }
                var DetailsPlayer = Singleton.Instance.PlayerList.ElementAt(pos);
                return View(DetailsPlayer);
            }
            else
            {
                int pos = 0;
                bool Finding = false;
                while (Finding == false)
                {
                    if (Convert.ToInt32(Singleton.Instance.player_list.ElementAt(pos).Id) == id)
                    {
                        Finding = true;
                    }
                    else
                    {
                        pos++;
                    }
                }
                var DetailsPlayer = Singleton.Instance.player_list.ElementAt(pos);
                return View(DetailsPlayer);
            }
        }

        // GET: Players/Create
        public ActionResult Create()
        {
            if (Singleton.Instance.PlayerList.Count != 0 || Singleton.Instance.player_list.Count() != 0)
            {
                return View();
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }            
        }

        // POST: Players/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                timer.Start();
                bool TypeListArt = false;
                string ListType = "";
                int IdNumber = 0;
                int NumberListCraft = Singleton.Instance.player_list.GetCount;
                int NumberListC = Singleton.Instance.PlayerList.Count;

                if (NumberListCraft != 0)
                {
                    TypeListArt = true;
                    if (NumberListCraft == 1 && Singleton.Instance.player_list.First().Id == 0)
                    {
                        IdNumber = 1;
                        ListType = "Lista Artesanal. ";
                        Singleton.Instance.player_list.ExtractAtStart();
                    }
                    else
                    {
                        IdNumber = NumberListCraft + 1;
                    }

                }

                if (NumberListC != 0)
                {
                    if (NumberListC == 1 && Singleton.Instance.PlayerList.First().Id == 0)
                    {
                        IdNumber = 1;

                        Singleton.Instance.PlayerList.RemoveFirst();

                        ListType = "Lista C#. ";
                        Singleton.Instance.PlayerList.RemoveFirst();
                    }
                    else
                    {
                        IdNumber = Singleton.Instance.PlayerList.Count + 1;
                    }
                }

                var newPlayer = new Models.Players
                {
                    Id = IdNumber,
                    Name = collection["Name"],
                    LastName = collection["LastName"],
                    Position = collection["Position"],
                    Salary = Convert.ToInt32(collection["Salary"]),
                    Club = collection["Club"]
                };

                if (TypeListArt == true)
                {
                    Singleton.Instance.player_list.InsertAtEnd(newPlayer);
                }
                else
                {
                    Singleton.Instance.PlayerList.AddLast(newPlayer);
                }

                //MEDIR TIEMPO Y GUARDARLO
                timer.Stop();
                var NewDescriptionTime = new Models.TimeDescription
                {
                    DescriptionTime = ListType + "Carga de datos de forma manual ",
                    NumberTime = Convert.ToString(timer.Elapsed.TotalMilliseconds)
                };
                Singleton.Instance.OperationTime.Add(NewDescriptionTime);

                return RedirectToAction(nameof(Index));
            }
            catch
            {

Views/Players/Create.cshtml
@model Lab1_KASR_MAGZ.Models.Players

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Players</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Club" class="control-label"></label>
                <input asp-for="Club" class="form-control" />
                <span asp-validation-for="Club" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Players/Delete.cshtml
@model Lab1_KASR_MAGZ.Models.Players

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this player?</h3>
<div>
    <h4>Players</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Club)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Club)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Players/Details.cshtml
@model Lab1_KASR_MAGZ.Models.Players

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Players</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Club)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Club)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Players/Edit.cshtml
@model Lab1_KASR_MAGZ.Models.Players

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Players</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Club" class="control-label"></label>
                <input asp-for="Club" class="form-control" />
                <span asp-validation-for="Club" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Players/Index.cshtml
@model IEnumerable<Lab1_KASR_MAGZ.Models.Players>


@{
    ViewData["Title"] = "Index";
}

<h1>Major League Soccer Database</h1>

<b><p>Which list do you want to use?</p></b>
<p>
    <a asp-action="CraftList">Craft list</a>
</p>
<p>
    <a asp-action="ListC">List C#</a>
</p>
<p>

</p>
<p>
</p>
<b><p>How do you want to upload the data?</p></b>

<b><p>IMPORT FILE</p></b>
<form asp-controller="Players" asp-action="Index" method="post" enctype="multipart/form-data">
    <input type="file" name="postedFile" value="" />
    <input type="submit" value="Import" />
</form>
<p>

</p>
<b><p>MANUAL</p></b>
<p>
    <a asp-action="Create">Create New</a>
</p>

<b><p>What do you want to search?</p></b>
<form action="Players/Searching" method="post">

    <input type="type" name="information" value="" />
    <button>Enviar</button>
</form>
<b><p>Search a salary</p></b>
<form action="Players/SearchingMajorSalary" method="post">
    <button>Major than</button>   <input type="number" name="information" value="" style='width:90px; height:30px;font-size:20px;color:blue' /> 
</form>
<form action="Players/SearchingMinorSalary" method="post">
    <button>Minor than</button>   <input type="number" name="information" value="" style='width:90px; height:30px;font-size:20px;color:blue' /> 
</form>
<form action="Players/SearchingEqualSalary" method="post">
    <button>Equal to</button>     <input type="number" name="information" value="" style='width:90px; height:30px;font-size:20px;color:blue' /> 
</form>
<p>
    <a asp-action="Download">Download Log</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Club)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Position)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Club)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Players/Searching.cshtml
@model IEnumerable<Lab1_KASR_MAGZ.Models.Players>

@{
    ViewData["Title"] = "Searching";
}

<h1>Results</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Club)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) 
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Club)
            </td>           
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="Return">Back to List</a>
</div>

Views/Players/SearchingEqualSalary.cshtml
@model IEnumerable<Lab1_KASR_MAGZ.Models.Players>

@{
    ViewData["Title"] = "SearchingEqualSalary";
}

<h1>Results</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Club)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Club)
            </td>            
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="Return">Back to List</a>
</div>

Views/Players/SearchingMajorSalary.cshtml
@model IEnumerable<Lab1_KASR_MAGZ.Models.Players>

@{
    ViewData["Title"] = "SearchingMajorSalary";
}

<h1>Results</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Club)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Club)
            </td>            
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="Return">Back to List</a>
</div>

Views/Players/SearchingMinorSalary.cshtml
@model IEnumerable<Lab1_KASR_MAGZ.Models.Players>

@{
    ViewData["Title"] = "SearchingMinorSalary";
}

<h1>Results</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Club)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Club)
            </td>
            
        </tr>
}
    </tbody>
</table>
<div>
    <a asp-action="Return">Back to List</a>
</div>